name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - name: project checkout
      uses: actions/checkout@v3
    - name: install SDL dependencies
      run: apt-get update && apt-get install -y build-essential libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev
    - name: pack
      run: make build && make pack
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: target/sdl2-pong.tar.gz
